Entity/Cities.php
<?php

namespace CMS\LocalizationBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Cities
 */
class Cities
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var locale_string
     */
    private $title;

    /**
     * @var string
     */
    private $alias;

    /**
     * @var Countries
     */
    private $country;

    /**
     * @var ArrayCollection
     */
    private $hotels;

    /**
     * @var ArrayCollection
     */
    private $restaurants;

    /**
     * @var ArrayCollection
     */
    private $hospitals;

    /**
     * @var \DateTime
     */
    private $date_create;

    /**
     * @var \DateTime
     */
    private $date_update;

    /**
     * @var integer
     */
    private $create_by;

    /**
     * @var integer
     */
    private $update_by;

    public function __construct()
    {
        $this->hotels = new ArrayCollection();
        $this->restaurants = new ArrayCollection();
        $this->hospitals = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param locale_string $title
     * @return Cities
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return locale_string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * @param string $alias
     * @return $this
     */
    public function setAlias($alias)
    {
        $this->alias = $alias;

        return $this;
    }

    /**
     * @return Countries
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * @param Countries $country
     * @return Cities
     */
    public function setCountry($country)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getHotels()
    {
        return $this->hotels;
    }

    /**
     * @param ArrayCollection $hotels
     * @return $this
     */
    public function setHotels($hotels)
    {
        $this->hotels = $hotels;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getRestaurants()
    {
        return $this->restaurants;
    }

    /**
     * @param ArrayCollection $restaurants
     * @return $this
     */
    public function setRestaurants($restaurants)
    {
        $this->restaurants = $restaurants;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getHospitals()
    {
        return $this->hospitals;
    }

    /**
     * @param ArrayCollection $hospitals
     * @return $this
     */
    public function setHospitals($hospitals)
    {
        $this->hospitals = $hospitals;

        return $this;
    }

    /**
     * @return int
     */
    public function getCreateBy()
    {
        return $this->create_by;
    }

    /**
     * @param int $create_by
     * @return Locale
     */
    public function setCreateBy($create_by)
    {
        $this->create_by = $create_by;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateCreate()
    {
        return $this->date_create;
    }

    /**
     * @param \DateTime $date_create
     * @return Locale
     */
    public function setDateCreate($date_create)
    {
        $this->date_create = new \DateTime();

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateUpdate()
    {
        return $this->date_update;
    }

    /**
     * @param \DateTime $date_update
     * @return Locale
     */
    public function setDateUpdate($date_update)
    {
        $this->date_update = new \DateTime();

        return $this;
    }

    /**
     * @return int
     */
    public function getUpdateBy()
    {
        return $this->update_by;
    }

    /**
     * @param int $update_by
     * @return Locale
     */
    public function setUpdateBy($update_by)
    {
        $this->update_by = $update_by;

        return $this;
    }
}

Form/CountriesType.php
<?php

namespace CMS\LocalizationBundle\Form;

use CMS\LocalizationBundle\Form\Types\LocaleTextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CountriesType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', LocaleTextType::class)
            ->add('alias')
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'CMS\LocalizationBundle\Entity\Countries'
        ));
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'cms_localizationbundle_countries';
    }
}

Controller/CountriesController.php
<?php

namespace CMS\LocalizationBundle\Controller;

use CMS\LocalizationBundle\Entity\Countries;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class CountriesController extends Controller
{
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction()
    {
        $service = $this->get('cms.localization.countries.service');

        return $this->render('LocalizationBundle:Countries:list.html.twig', array(
            'countries' => $service->findAll()
        ));
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function createAction(Request $request)
    {
        $service = $this->get('cms.localization.countries.service');

        $form = $service->generateForm();

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $service->create($form->getData());

                return $this->redirect($this->generateUrl('cms_localization_countries_list'));
            }
        }

        return $this->render('LocalizationBundle:Countries:edit.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function editAction(Request $request, $id)
    {
        $service = $this->get('cms.localization.countries.service');

        $form = $service->generateForm($service->findOneById($id));

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $service->update($form->getData());

                return $this->redirect($this->generateUrl('cms_localization_countries_list'));
            }
        }

        return $this->render('LocalizationBundle:Countries:edit.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction(Request $request, $id)
    {
        $service = $this->get('cms.localization.countries.service');

        $service->delete($id);

        return $this->redirect($this->generateUrl('cms_localization_countries_list'));
    }
}

Resources/views/Countries/edit.html.twig
{% extends "DashboardBundle:Layout:base.html.twig" %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts 'bundles/localization/js/localization_form.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}

{% block body %}
    {% embed 'LocalizationBundle::main.html.twig' %}
        {% block main %}
            <div class="row">
                {% form_theme form 'LocalizationBundle::fields.html.twig' %}
                <div class="col-md-12">
                    {{ show_locale_tabs() }}
                    <br/>

                    {{ form_start(form, {'method': 'POST', 'attr': {'class': 'form-horizontal'}}) }}
                        <div class="row">
                            <div class="col-md-12">
                                {{ form_errors(form) }}
                                {{ form_row(form.title,{
                                    'label': 'Title'|trans({},'messages'),
                                }) }}
                                {{ form_row(form.alias,{
                                    'label': 'Alias'|trans({},'messages'),
                                }) }}
                                {{ form_rest(form) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="well well-sm text-right">
                                    <input type="submit" class="btn btn-primary btn-sm" data-loading-text="Saving..."
                                           value="{{ 'Save'|trans({}, 'systems') }}"/>
                                    <a href="javascript:history.go(-1)"
                                       class="btn btn-default btn-sm">{{ 'Cancel'|trans({}, 'systems') }}</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}

Resources/views/Countries/list.html.twig
{% extends "DashboardBundle:Layout:base.html.twig" %}

{% block body %}
    {% embed 'LocalizationBundle::main.html.twig' %}
        {% block panelButtons %}
            <a href="{{ url('cms_localization_countries_create') }}"
               class="glyphicon glyphicon-plus btn btn-success btn-xs">{{ 'Add'|trans }}</a>
        {% endblock %}

        {% block main %}
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <th><input type="checkbox" data-action="selectAll"/></th>
                    <th>ID</th>
                    <th>{{ 'Title'|trans }}</th>
                    <th>{{ 'Date'|trans }}</th>
                    <th></th>
                    <th></th>
                    </thead>
                    <tbody>
                    {% for country in countries %}
                        <tr>
                            <td><input type="checkbox" value="{{ country.id }}" name="mark[]"/></td>
                            <td>{{ country.id }}</td>
                            <td>
                                <a href="{{ url('cms_localization_countries_edit', {id: country.id}) }}">
                                    {{ country.title|locale }}
                                </a>
                            </td>
                            <td>{{ country.dateCreate|date('d.m.Y') }}</td>
                            <td><a href='{{ url('cms_localization_countries_edit', {id: country.id}) }}'><span
                                            class="glyphicon lead text-primary glyphicon-pencil"></span></a></td>
                            <td><a href='{{ url('cms_localization_countries_delete', {id: country.id}) }}'><span
                                            class="glyphicon lead text-danger glyphicon-remove-circle"></span></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}